### PR TITLE
Templates for Issues

### PR DESCRIPTION
**Pull request by beorostica**
This pull request is intended to resolve issue https://github.com/cncastillo/KomaMRI.jl/issues/228

### CODE REVIEW

**Comment by cncastillo** [comment]
Change feature request to .yaml

**Comment by beorostica** [comment]
> Change feature request to .yaml

Addressed in https://github.com/cncastillo/KomaMRI.jl/pull/254/commits/d2346699665f93e61aeb7186010542713382515a

**Comment by cncastillo** [comment]
Put in an issue al the warnings that we are getting for the docs.

**Comment by beorostica** [comment]
> Put in an issue al the warnings that we are getting for the docs.

Addressed in https://github.com/cncastillo/KomaMRI.jl/issues/255

**Pull request merged**
